# -*- coding: utf-8 -*-
"""Copy of test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uPMeuOLpAq1LjLobEB6EwEu__NDBKHFU
"""

from google.colab import drive
drive.mount('/content/drive')

"""unzipping data"""

import zipfile
import os

# 1. Define your paths
zip_path = '/content/drive/MyDrive/EPICS/Copy of brain_tumor.zip'  # Update if your zip name is different
extract_path = '/content/drive/MyDrive/EPICS'

# 2. Create the target directory
os.makedirs(extract_path, exist_ok=True)

# 3. Unzip the file
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print(f"Files extracted to: {extract_path}")

"""rotation"""

import os
from PIL import Image
from pathlib import Path

# Define your paths
input_folder = '/content/drive/MyDrive/EPICS/00001'  # Path to your unzipped images
output_folder = '/content/drive/MyDrive/EPICS/rotated1'

# Create output directory if it doesn't exist
os.makedirs(output_folder, exist_ok=True)

# Define valid image extensions
valid_extensions = ('.jpg', '.jpeg', '.png', '.bmp')

print("Starting rotation of 2000 images...")

for filename in os.listdir(input_folder):
    if filename.lower().endswith(valid_extensions):
        img_path = os.path.join(input_folder, filename)

        with Image.open(img_path) as img:
            # Rotate 90 degrees clockwise to make them upright
            # Use Image.ROTATE_270 for clockwise or Image.ROTATE_90 for counter-clockwise
            rotated_img = img.transpose(Image.ROTATE_270)

            # Save to the new folder
            rotated_img.save(os.path.join(output_folder, filename))

print(f"Done! All images rotated and saved to: {output_folder}")

"""skull stripping"""

!python skull_strip.py batch --input_dir "/content/drive/MyDrive/EPICS/rotated2" --output_dir "/content/drive/MyDrive/EPICS/dataset_stripped2" --check

"""skull stripping diagnose"""

!python /content/skull_strip.py diagnose --input_dir "/content/drive/MyDrive/EPICS/retrying_stripped"

!python /content/skull_strip.py diagnose --input_dir "/content/drive/MyDrive/EPICS/retrying_stripped1"

!python /content/skull_strip.py diagnose --input_dir "/content/drive/MyDrive/EPICS/retrying_stripped2"

"""sequence filtering(one image)"""

import cv2
import numpy as np
from pathlib import Path

def get_intensity_stats(image_path):
    img = cv2.imread(str(image_path), cv2.IMREAD_GRAYSCALE)
    # Calculate mean brightness of the brain tissue only
    mask = img > 10 # Ignore black background
    if not np.any(mask): return 0
    return np.mean(img[mask])

# Logic:
# T1: Generally darker gray matter (lower mean)
# FLAIR/T1-Contrast: Brighter lesions or white matter (higher mean)

"""sequence filtering actual"""

import os
import shutil
import cv2
import numpy as np
from pathlib import Path

# 1. The "Engine" (Your function)
def get_intensity_stats(image_path):
    img = cv2.imread(str(image_path), cv2.IMREAD_GRAYSCALE)
    if img is None:
        return 0 # Skip corrupted images

    # Calculate mean brightness of the brain tissue only
    mask = img > 10 # Ignore black background
    if not np.any(mask):
        return 0
    return np.mean(img[mask])

# 2. Define your folders
# We are using the output from your skull-stripping step!
input_dir = "/content/mri_dataset_stripped"
t1_dark_dir = "/content/mri_dataset_T1_Dark"
flair_bright_dir = "/content/mri_dataset_FLAIR_Bright"

# Create the output folders
os.makedirs(t1_dark_dir, exist_ok=True)
os.makedirs(flair_bright_dir, exist_ok=True)

print("Analyzing intensities and sorting sequences...")

# 3. The Loop (How it accesses the paths)
processed_count = 0
for filename in os.listdir(input_dir):
    if filename.lower().endswith(('.jpg', '.jpeg', '.png')):

        # THIS creates the actual path (e.g., /content/mri_dataset_stripped/0001.jpg)
        full_image_path = os.path.join(input_dir, filename)

        # Pass the path to your function
        mean_brightness = get_intensity_stats(full_image_path)

        # 4. The Sorting Logic
        # (You may need to adjust the number '65' depending on your specific dataset)
        if mean_brightness < 65:
            # It's dark (likely T1)
            shutil.copy(full_image_path, os.path.join(t1_dark_dir, filename))
        else:
            # It's bright (likely FLAIR or T1-Contrast)
            shutil.copy(full_image_path, os.path.join(flair_bright_dir, filename))

        processed_count += 1

print(f"Done! Sorted {processed_count} images based on intensity.")
print(f"Dark/T1 scans are in: {t1_dark_dir}")
print(f"Bright/FLAIR scans are in: {flair_bright_dir}")

"""orientation preview"""

!python mri_orientation_sort.py preview --input_dir "/content/drive/MyDrive/EPICS/rotated1" --n 5

import os

# Define the path to your shortcut
# Replace 'Shared_Folder_Name' with the actual name of the folder shortcut
path = "/content/drive/MyDrive/EPICS"

# Verify the connection by listing files
print(os.listdir(path))

"""Dataset reorganization"""

import os
import shutil
import random

# 1. Define your current paths (Update these if they are slightly different in your Drive)
dark_dir = '/content/drive/MyDrive/EPICS/dark_dataset'
bright_dir = '/content/drive/MyDrive/EPICS/Bright_Dataset'

# The new master folder we are creating for PyTorch
output_dir = '/content/drive/MyDrive/EPICS/orientation_dataset'

# Your exact folder names
classes = ['axial', 'coronal', 'sagitall']

print("Creating PyTorch folder structure...")

# 2. Create the empty train/val structure
for split in ['train', 'val']:
    for cls in classes:
        os.makedirs(os.path.join(output_dir, split, cls), exist_ok=True)

# 3. Function to pool, shuffle, and split files
def process_and_split(class_name):
    all_files = []

    # Grab images from the dark folder
    dark_path = os.path.join(dark_dir, class_name)
    if os.path.exists(dark_path):
        all_files.extend([os.path.join(dark_path, f) for f in os.listdir(dark_path) if f.lower().endswith(('.png', '.jpg', '.jpeg'))])

    # Grab images from the bright folder
    bright_path = os.path.join(bright_dir, class_name)
    if os.path.exists(bright_path):
        all_files.extend([os.path.join(bright_path, f) for f in os.listdir(bright_path) if f.lower().endswith(('.png', '.jpg', '.jpeg'))])

    # Shuffle them so dark/bright are mixed randomly
    random.shuffle(all_files)

    # Calculate the 80/20 split index
    split_idx = int(len(all_files) * 0.8)
    train_files = all_files[:split_idx]
    val_files = all_files[split_idx:]

    # Copy files to the new train and val folders
    for f in train_files:
        # Give files a unique prefix just in case a dark and bright file share the exact same name (e.g., '001.jpg')
        folder_origin = "dark_" if dark_dir in f else "bright_"
        new_name = folder_origin + os.path.basename(f)
        shutil.copy(f, os.path.join(output_dir, 'train', class_name, new_name))

    for f in val_files:
        folder_origin = "dark_" if dark_dir in f else "bright_"
        new_name = folder_origin + os.path.basename(f)
        shutil.copy(f, os.path.join(output_dir, 'val', class_name, new_name))

    print(f"{class_name.capitalize()}: {len(train_files)} Train images, {len(val_files)} Validation images.")

# 4. Run the process for all three classes
for cls in classes:
    process_and_split(cls)

print(f"\nDone! Your dataset is ready for training at: {output_dir}")

"""Training for seperation of axial, sagitall and coronal

---


"""

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, models, transforms
from torch.utils.data import DataLoader
import os
import copy
import time

# 1. Setup Device
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(f"Training on device: {device}")

# 2. Define Data Transforms
# ResNet expects 224x224 images and specific normalization
data_transforms = {
    'train': transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.RandomRotation(10), # Slight rotation to prevent memorization
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ]),
    'val': transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ]),
}

# 3. Load the Dataset
data_dir = '/content/drive/MyDrive/EPICS/orientation_dataset'

image_datasets = {x: datasets.ImageFolder(os.path.join(data_dir, x), data_transforms[x])
                  for x in ['train', 'val']}

dataloaders = {x: DataLoader(image_datasets[x], batch_size=16, shuffle=True, num_workers=2)
               for x in ['train', 'val']}

dataset_sizes = {x: len(image_datasets[x]) for x in ['train', 'val']}
class_names = image_datasets['train'].classes
print(f"Classes found: {class_names}")

# 4. Initialize Pre-trained ResNet18
# Using weights=models.ResNet18_Weights.DEFAULT to download pre-trained weights
model = models.resnet18(weights=models.ResNet18_Weights.DEFAULT)

# Freeze early layers so we don't destroy the pre-trained vision features
for param in model.parameters():
    param.requires_grad = False

# Replace the final layer to output our 3 classes
num_ftrs = model.fc.in_features
model.fc = nn.Linear(num_ftrs, len(class_names))
model = model.to(device)

# 5. Define Loss and Optimizer
criterion = nn.CrossEntropyLoss()
# We only pass the parameters of the final layer to the optimizer
optimizer = optim.Adam(model.fc.parameters(), lr=0.001)

# 6. Training Loop
num_epochs = 10
best_model_wts = copy.deepcopy(model.state_dict())
best_acc = 0.0

print("\nStarting Training...")
since = time.time()

for epoch in range(num_epochs):
    print(f'Epoch {epoch+1}/{num_epochs}')
    print('-' * 10)

    for phase in ['train', 'val']:
        if phase == 'train':
            model.train()  # Set model to training mode
        else:
            model.eval()   # Set model to evaluate mode

        running_loss = 0.0
        running_corrects = 0

        # Iterate over data
        for inputs, labels in dataloaders[phase]:
            inputs = inputs.to(device)
            labels = labels.to(device)

            optimizer.zero_grad()

            # Forward pass: track history if only in train
            with torch.set_grad_enabled(phase == 'train'):
                outputs = model(inputs)
                _, preds = torch.max(outputs, 1)
                loss = criterion(outputs, labels)

                # Backward pass & optimize only if in training phase
                if phase == 'train':
                    loss.backward()
                    optimizer.step()

            # Statistics
            running_loss += loss.item() * inputs.size(0)
            running_corrects += torch.sum(preds == labels.data)

        epoch_loss = running_loss / dataset_sizes[phase]
        epoch_acc = running_corrects.double() / dataset_sizes[phase]

        print(f'{phase.capitalize()} Loss: {epoch_loss:.4f} Acc: {epoch_acc:.4f}')

        # Deep copy the model if it has the best validation accuracy so far
        if phase == 'val' and epoch_acc > best_acc:
            best_acc = epoch_acc
            best_model_wts = copy.deepcopy(model.state_dict())
    print()

time_elapsed = time.time() - since
print(f'Training complete in {time_elapsed // 60:.0f}m {time_elapsed % 60:.0f}s')
print(f'Best Validation Accuracy: {best_acc:4f}')

# Load best model weights and save
model.load_state_dict(best_model_wts)
save_path = '/content/drive/MyDrive/EPICS/mri_orientation_model.pth'
torch.save(model.state_dict(), save_path)
print(f"Model saved to: {save_path}")

"""
seperation using model"""

import torch
import torch.nn as nn
from torchvision import models, transforms
from PIL import Image
import os
import shutil

# 1. Setup Device and Classes
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
class_names = ['axial', 'coronal', 'sagitall'] # Must match the exact order from training

# 2. Rebuild the Model Architecture and Load Your Weights
print("Loading model...")
model = models.resnet18(weights=None) # We don't need the default weights anymore
num_ftrs = model.fc.in_features
model.fc = nn.Linear(num_ftrs, len(class_names))

# Load your custom trained weights
model_path = '/content/drive/MyDrive/EPICS/mri_orientation_model.pth'
model.load_state_dict(torch.load(model_path, map_location=device))
model = model.to(device)
model.eval() # CRITICAL: Sets the model to "prediction" mode, not "training" mode
print("Model loaded successfully!")

# 3. Define the exact same vision transforms used in Validation
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

# 4. Define your Folders
# ---> CHANGE THIS to the folder containing your unsorted images <---
input_folder = '/content/drive/MyDrive/EPICS/dataset_FLAIR_Bright'

# Where the model should put the sorted images
output_base_folder = '/content/drive/MyDrive/EPICS/dataset_FLAIR_Bright_seperatedByModel'

# Create output directories
for cls in class_names:
    os.makedirs(os.path.join(output_base_folder, cls), exist_ok=True)

# 5. The Sorting Loop
print(f"Starting automatic sorting from: {input_folder}")
processed_count = 0

# Get all images
image_files = [f for f in os.listdir(input_folder) if f.lower().endswith(('.png', '.jpg', '.jpeg'))]

# Tell PyTorch we don't need to calculate gradients (makes predictions much faster)
with torch.no_grad():
    for filename in image_files:
        img_path = os.path.join(input_folder, filename)

        try:
            # Open image and apply transforms
            img = Image.open(img_path).convert('RGB')
            img_tensor = transform(img).unsqueeze(0).to(device) # Add batch dimension

            # Make the prediction
            outputs = model(img_tensor)
            _, predicted_idx = torch.max(outputs, 1)
            predicted_class = class_names[predicted_idx.item()]

            # Copy the file to the predicted folder
            dest_path = os.path.join(output_base_folder, predicted_class, filename)
            shutil.copy(img_path, dest_path)

            processed_count += 1
            if processed_count % 100 == 0:
                print(f"Sorted {processed_count} images...")

        except Exception as e:
            print(f"Skipping {filename} due to error: {e}")

print(f"\nSuccess! Automatically sorted {processed_count} images into {output_base_folder}")

"""GAN Code

"""

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision.transforms as transforms
import torchvision.utils as vutils
from torch.utils.data import Dataset, DataLoader
from PIL import Image
import matplotlib.pyplot as plt
import os
import glob

# 1. Custom Dataset (No weird subfolder rules required)
class SingleFolderDataset(Dataset):
    def __init__(self, folder_path, transform=None):
        # Grabs all jpg, jpeg, and png files in the exact folder
        self.image_paths = []
        for ext in ('*.jpg', '*.jpeg', '*.png'):
            self.image_paths.extend(glob.glob(os.path.join(folder_path, ext)))
            self.image_paths.extend(glob.glob(os.path.join(folder_path, ext.upper())))

        self.transform = transform

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        img_path = self.image_paths[idx]
        image = Image.open(img_path).convert('RGB')
        if self.transform:
            image = self.transform(image)
        return image, 0 # The '0' is a dummy label because GANs don't need class labels

# 2. GAN Architectures
# Generator
class Generator(nn.Module):
    def __init__(self, nz=100, ngf=64, nc=3):
        super(Generator, self).__init__()
        self.main = nn.Sequential(
            nn.ConvTranspose2d(nz, ngf * 8, 4, 1, 0, bias=False),
            nn.BatchNorm2d(ngf * 8),
            nn.ReLU(True),
            nn.ConvTranspose2d(ngf * 8, ngf * 4, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ngf * 4),
            nn.ReLU(True),
            nn.ConvTranspose2d(ngf * 4, ngf * 2, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ngf * 2),
            nn.ReLU(True),
            nn.ConvTranspose2d(ngf * 2, ngf, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ngf),
            nn.ReLU(True),
            nn.ConvTranspose2d(ngf, nc, 4, 2, 1, bias=False),
            nn.Tanh()
        )
    def forward(self, input):
        return self.main(input)

# Discriminator
class Discriminator(nn.Module):
    def __init__(self, nc=3, ndf=64):
        super(Discriminator, self).__init__()
        self.main = nn.Sequential(
            nn.Conv2d(nc, ndf, 4, 2, 1, bias=False),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Conv2d(ndf, ndf * 2, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ndf * 2),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Conv2d(ndf * 2, ndf * 4, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ndf * 4),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Conv2d(ndf * 4, ndf * 8, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ndf * 8),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Conv2d(ndf * 8, 1, 4, 1, 0, bias=False),
            nn.Sigmoid()
        )
    def forward(self, input):
        return self.main(input)

# ... (Keep your Custom Dataset and Generator/Discriminator classes the same) ...

# 3. The UPDATED Core Training Function
def train_gan(folder_path, save_name, num_epochs=500):
    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    print(f"\n{'='*50}\nStarting Training for: {os.path.basename(save_name)}\n{'='*50}")

    # Check if folder has images
    if not os.path.exists(folder_path):
        print(f"ERROR: Folder {folder_path} does not exist. Skipping.")
        return

    # Hyperparameters (UPDATED for stability)
    batch_size = 32
    image_size = 64
    nz = 100
    lr = 0.0001 # LOWERED from 0.0002 to prevent sudden explosions
    beta1 = 0.5

    # Setup Dataset
    dataset = SingleFolderDataset(folder_path, transform=transforms.Compose([
                               transforms.Resize(image_size),
                               transforms.CenterCrop(image_size),
                               transforms.ToTensor(),
                               transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)),
                           ]))

    if len(dataset) == 0:
        print(f"ERROR: No images found in {folder_path}. Skipping.")
        return

    dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True, num_workers=2)

    # Initialize Networks
    netG = Generator().to(device)
    netD = Discriminator().to(device)

    criterion = nn.BCELoss()
    fixed_noise = torch.randn(64, nz, 1, 1, device=device)
    optimizerD = optim.Adam(netD.parameters(), lr=lr, betas=(beta1, 0.999))
    optimizerG = optim.Adam(netG.parameters(), lr=lr, betas=(beta1, 0.999))

    # Training Loop
    for epoch in range(num_epochs):
        for i, data in enumerate(dataloader, 0):
            # Update Discriminator
            netD.zero_grad()
            real_cpu = data[0].to(device)
            b_size = real_cpu.size(0)

            # ---> LABEL SMOOTHING APPLIED HERE <---
            # We use 0.9 instead of 1.0 to prevent the discriminator from getting too confident
            label = torch.full((b_size,), 0.9, dtype=torch.float, device=device)

            output = netD(real_cpu).view(-1)
            errD_real = criterion(output, label)
            errD_real.backward()

            noise = torch.randn(b_size, nz, 1, 1, device=device)
            fake = netG(noise)
            label.fill_(0.0) # Fakes stay at 0.0

            output = netD(fake.detach()).view(-1)
            errD_fake = criterion(output, label)
            errD_fake.backward()

            errD = errD_real + errD_fake
            optimizerD.step()

            # Update Generator
            netG.zero_grad()
            label.fill_(0.9) # Generator wants to hit 0.9 now

            output = netD(fake).view(-1)
            errG = criterion(output, label)
            errG.backward()
            optimizerG.step()

        # Print update every 100 epochs
        if (epoch + 1) % 100 == 0:
            print(f'Epoch [{epoch+1}/{num_epochs}] | Loss_D: {errD.item():.4f} | Loss_G: {errG.item():.4f}')

    # Save the model
    torch.save(netG.state_dict(), save_name)
    print(f"Success! Model saved to {save_name}")

    del netG, netD, optimizerG, optimizerD, real_cpu, fake
    torch.cuda.empty_cache()

# 4. The Execution Queue
base_drive = '/content/drive/MyDrive/EPICS'

# We are restarting the bright_axial one since it collapsed, and keeping the last two
training_queue = [

    {"path": "/content/drive/MyDrive/EPICS/dataset_FLAIR_Bright_seperatedByModel/sagitall",
     "save": "/content/drive/MyDrive/EPICS/gen_FLAIR_bright_sagitall.pth"}
]

# Run the loop
print("Initiating Master Training Loop...")
for task in training_queue:
    train_gan(folder_path=task["path"], save_name=task["save"], num_epochs=500)

print("\nAll remaining GANs have finished training!")

"""The Mass Production Script"""

import torch
import torch.nn as nn
import torchvision.utils as vutils
import os

# 1. Redefine your exact Generator architecture
class Generator(nn.Module):
    def __init__(self, nz=100, ngf=64, nc=3):
        super(Generator, self).__init__()
        self.main = nn.Sequential(
            nn.ConvTranspose2d(nz, ngf * 8, 4, 1, 0, bias=False),
            nn.BatchNorm2d(ngf * 8),
            nn.ReLU(True),
            nn.ConvTranspose2d(ngf * 8, ngf * 4, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ngf * 4),
            nn.ReLU(True),
            nn.ConvTranspose2d(ngf * 4, ngf * 2, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ngf * 2),
            nn.ReLU(True),
            nn.ConvTranspose2d(ngf * 2, ngf, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ngf),
            nn.ReLU(True),
            nn.ConvTranspose2d(ngf, nc, 4, 2, 1, bias=False),
            nn.Tanh()
        )
    def forward(self, input):
        return self.main(input)

# 2. Setup Device and Parameters
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(f"Generating on: {device}")

nz = 100 # Size of the random noise vector
num_images_to_generate = 200 # Adjust this if you want more/less fakes per category

# 3. Define the Models and their Output Folders (Updated with your exact paths)
output_base = '/content/drive/MyDrive/EPICS/synthetic_fakes'

production_queue = [
    {"weights": "/content/drive/MyDrive/EPICS/gen_T1_dark_axial.pth",      "out_dir": f"{output_base}/dark/axial"},
    {"weights": "/content/drive/MyDrive/EPICS/gen_T1_dark_coronal.pth",    "out_dir": f"{output_base}/dark/coronal"},
    {"weights": "/content/drive/MyDrive/EPICS/gen_T1_dark_sagitall.pth",   "out_dir": f"{output_base}/dark/sagitall"},
    {"weights": "/content/drive/MyDrive/EPICS/gen_FLAIR_bright_axial.pth", "out_dir": f"{output_base}/bright/axial"},
    {"weights": "/content/drive/MyDrive/EPICS/gen_FLAIR_bright_coronal.pth","out_dir": f"{output_base}/bright/coronal"},
    {"weights": "/content/drive/MyDrive/EPICS/gen_FLAIR_bright_sagitall.pth","out_dir": f"{output_base}/bright/sagitall"}
]

# 4. The Generation Loop
print(f"Starting mass production of {num_images_to_generate} images per category...")

for task in production_queue:
    weights_path = task["weights"]
    out_dir = task["out_dir"]

    if not os.path.exists(weights_path):
        print(f"⚠️ Skipping {os.path.basename(weights_path)} - File not found!")
        continue

    # Create the output directory
    os.makedirs(out_dir, exist_ok=True)

    # Initialize a fresh Generator and load your trained weights
    netG = Generator().to(device)
    netG.load_state_dict(torch.load(weights_path, map_location=device))
    netG.eval() # CRITICAL: Sets the model to generation/evaluation mode

    print(f"Generating fakes for: {os.path.basename(out_dir)}...")

    # Turn off gradients to save memory and speed up generation
    with torch.no_grad():
        for i in range(num_images_to_generate):
            # 1. Create pure random noise
            noise = torch.randn(1, nz, 1, 1, device=device)

            # 2. Feed it to the Generator to hallucinate an image
            fake_image = netG(noise)

            # 3. Save the image (normalize=True converts the math back into normal pixel colors)
            save_path = os.path.join(out_dir, f"synthetic_{i+1:04d}.jpg")
            vutils.save_image(fake_image.detach(), save_path, normalize=True)

print(f"\n✅ Success! 1,200 synthetic deepfakes have been generated and saved to: {output_base}")

"""Resizing of Real images"""

import os
from PIL import Image

# 1. Define your paths
# The base folder where your original, high-res real images are currently separated
base_real_dir = '/content/drive/MyDrive/EPICS/dataset_FLAIR_Bright_seperatedByModel' # We'll do dark first, then bright
# The new folder where the 64x64 real images will be saved
output_base_dir = '/content/drive/MyDrive/EPICS/real_64x64/Bright'

planes = ['axial', 'coronal', 'sagitall']

print("Starting the downsampling process...")

processed_count = 0

for plane in planes:
    input_dir = os.path.join(base_real_dir, plane)
    output_dir = os.path.join(output_base_dir, plane)

    # Create the target folders if they don't exist
    os.makedirs(output_dir, exist_ok=True)

    if not os.path.exists(input_dir):
        print(f"Skipping {plane} - folder not found.")
        continue

    # Process each image
    for filename in os.listdir(input_dir):
        if filename.lower().endswith(('.jpg', '.jpeg', '.png')):
            img_path = os.path.join(input_dir, filename)

            try:
                with Image.open(img_path) as img:
                    # Resize to exactly 64x64 to match the GAN fakes
                    # LANCZOS is the highest quality downsampling filter
                    resized_img = img.resize((64, 64), Image.Resampling.LANCZOS)

                    # Save to the new directory
                    resized_img.save(os.path.join(output_dir, filename))
                    processed_count += 1
            except Exception as e:
                print(f"Could not process {filename}: {e}")

print(f"\nDone! Successfully resized {processed_count} Real images to 64x64.")
print(f"Saved to: {output_base_dir}")

"""Master Data set Merger"""

import os
import shutil
import random

real_base_dir = '/content/drive/MyDrive/EPICS/real_64x64'
fake_base_dir = '/content/drive/MyDrive/EPICS/synthetic_fakes'
final_dataset_dir = '/content/drive/MyDrive/EPICS/final_deepfake_dataset'

print("Preparing to merge datasets...")

# Create the exact PyTorch structure
classes = ['real', 'fake']
splits = ['train', 'val']

for split in splits:
    for cls in classes:
        os.makedirs(os.path.join(final_dataset_dir, split, cls), exist_ok=True)

def gather_and_split(source_dir, class_name):
    all_files = []
    for root, _, files in os.walk(source_dir):
        for file in files:
            if file.lower().endswith(('.png', '.jpg', '.jpeg')):
                all_files.append(os.path.join(root, file))

    if len(all_files) == 0:
        print(f"⚠️ Still seeing 0 files in {source_dir}. Try remounting your Drive!")
        return

    random.shuffle(all_files)

    # 80% Train, 20% Validation Split
    split_idx = int(len(all_files) * 0.8)
    train_files = all_files[:split_idx]
    val_files = all_files[split_idx:]

    for idx, f in enumerate(train_files):
        shutil.copy(f, os.path.join(final_dataset_dir, 'train', class_name, f"{class_name}_train_{idx:05d}.jpg"))

    for idx, f in enumerate(val_files):
        shutil.copy(f, os.path.join(final_dataset_dir, 'val', class_name, f"{class_name}_val_{idx:05d}.jpg"))

    print(f"✅ {class_name.capitalize()}: {len(train_files)} Train images, {len(val_files)} Validation images.")

gather_and_split(real_base_dir, 'real')
gather_and_split(fake_base_dir, 'fake')

print(f"\nDataset successfully merged and ready for training at: {final_dataset_dir}")

"""Training the Deepfake Detector"""

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, models, transforms
from torch.utils.data import DataLoader
import os
import copy
import time

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(f"Training Detector on: {device}")

# Data Transforms (Upscaling your 64x64 back to 224x224 for the EfficientNet architecture)
data_transforms = {
    'train': transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ]),
    'val': transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ]),
}

data_dir = '/content/drive/MyDrive/EPICS/final_deepfake_dataset'

image_datasets = {x: datasets.ImageFolder(os.path.join(data_dir, x), data_transforms[x])
                  for x in ['train', 'val']}

dataloaders = {x: DataLoader(image_datasets[x], batch_size=32, shuffle=True, num_workers=2)
               for x in ['train', 'val']}

dataset_sizes = {x: len(image_datasets[x]) for x in ['train', 'val']}
class_names = image_datasets['train'].classes
print(f"Classes found: {class_names}")

# Initialize EfficientNet-B0
model = models.efficientnet_b0(weights=models.EfficientNet_B0_Weights.DEFAULT)

# Replace the final classification head for our 2 classes (Real vs Fake)
num_ftrs = model.classifier[1].in_features
model.classifier[1] = nn.Linear(num_ftrs, len(class_names))
model = model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.0001)

num_epochs = 10
best_model_wts = copy.deepcopy(model.state_dict())
best_acc = 0.0

print("\nHunting Deepfakes (Training started)...")
since = time.time()

for epoch in range(num_epochs):
    print(f'Epoch {epoch+1}/{num_epochs}')
    print('-' * 10)

    for phase in ['train', 'val']:
        if phase == 'train':
            model.train()
        else:
            model.eval()

        running_loss = 0.0
        running_corrects = 0

        for inputs, labels in dataloaders[phase]:
            inputs = inputs.to(device)
            labels = labels.to(device)

            optimizer.zero_grad()

            with torch.set_grad_enabled(phase == 'train'):
                outputs = model(inputs)
                _, preds = torch.max(outputs, 1)
                loss = criterion(outputs, labels)

                if phase == 'train':
                    loss.backward()
                    optimizer.step()

            running_loss += loss.item() * inputs.size(0)
            running_corrects += torch.sum(preds == labels.data)

        epoch_loss = running_loss / dataset_sizes[phase]
        epoch_acc = running_corrects.double() / dataset_sizes[phase]

        print(f'{phase.capitalize()} Loss: {epoch_loss:.4f} Acc: {epoch_acc:.4f}')

        if phase == 'val' and epoch_acc > best_acc:
            best_acc = epoch_acc
            best_model_wts = copy.deepcopy(model.state_dict())
    print()

time_elapsed = time.time() - since
print(f'Training complete in {time_elapsed // 60:.0f}m {time_elapsed % 60:.0f}s')
print(f'Best Validation Accuracy: {best_acc:4f}')

model.load_state_dict(best_model_wts)
save_path = '/content/drive/MyDrive/EPICS/deepfake_detector_efficientnet.pth'
torch.save(model.state_dict(), save_path)
print(f"Detector saved to: {save_path}")

"""Testing of Detection"""

import torch
import torch.nn as nn
from torchvision import models, transforms
from PIL import Image
import torch.nn.functional as F

# 1. Setup Device and Classes
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
class_names = ['fake', 'real'] # This must match exactly what PyTorch found during training

# 2. Rebuild the Architecture and Load Your Masterpiece
print("Waking up the Deepfake Detector...")
model = models.efficientnet_b0(weights=None)
num_ftrs = model.classifier[1].in_features
model.classifier[1] = nn.Linear(num_ftrs, len(class_names))

# Load your custom weights
model_path = '/content/drive/MyDrive/EPICS/deepfake_detector_efficientnet.pth'
model.load_state_dict(torch.load(model_path, map_location=device))
model = model.to(device)
model.eval() # CRITICAL: Set to prediction mode

# 3. Define the exact same vision transforms used in training
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

# 4. The Prediction Engine
def scan_for_deepfakes(image_path):
    try:
        # Open and format the image
        img = Image.open(image_path).convert('RGB')
        img_tensor = transform(img).unsqueeze(0).to(device)

        # Make the prediction
        with torch.no_grad():
            outputs = model(img_tensor)

            # Convert the raw math into readable percentages using Softmax
            probabilities = F.softmax(outputs, dim=1)[0]
            confidence, predicted_idx = torch.max(probabilities, 0)

        predicted_class = class_names[predicted_idx.item()].upper()
        confidence_pct = confidence.item() * 100

        print(f"\nScan Complete for: {image_path.split('/')[-1]}")
        print("-" * 30)
        print(f"Verdict:    {predicted_class}")
        print(f"Confidence: {confidence_pct:.2f}%")

    except Exception as e:
        print(f"Error scanning image: {e}")

# ==========================================
# 5. TEST IT HERE
# ==========================================
# Change this path to point to any image in your Drive to test it!
test_image_path = '/content/drive/MyDrive/EPICS/synthetic_fakes/dark/axial/synthetic_0026.jpg'

scan_for_deepfakes(test_image_path)

"""FINALLLLLLLYYYYYYYYYYY Gradio"""

!pip install gradio

import gradio as gr
import torch
import torch.nn as nn
from torchvision import models, transforms
from PIL import Image
import torch.nn.functional as F

# 1. Setup Device and Load Model
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
class_names = ['fake', 'real']

print("Loading the EPICS Deepfake Hunter...")
model = models.efficientnet_b0(weights=None)
num_ftrs = model.classifier[1].in_features
model.classifier[1] = nn.Linear(num_ftrs, len(class_names))

# Load your custom trained weights
model_path = '/content/drive/MyDrive/EPICS/deepfake_detector_efficientnet.pth'
model.load_state_dict(torch.load(model_path, map_location=device))
model = model.to(device)
model.eval()

# 2. Define Transforms (Same as training)
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

# 3. The Core Prediction Function
def predict_image(img):
    if img is None:
        return None

    # Ensure the image is in RGB format
    img = img.convert('RGB')
    img_tensor = transform(img).unsqueeze(0).to(device)

    # Make the prediction
    with torch.no_grad():
        outputs = model(img_tensor)
        # Convert raw math to percentages (0.0 to 1.0)
        probabilities = F.softmax(outputs, dim=1)[0]

    # Format the output for Gradio's Label component (e.g., {"REAL": 0.98, "FAKE": 0.02})
    results = {class_names[i].upper(): float(probabilities[i]) for i in range(len(class_names))}
    return results

# 4. Build the Graphical Interface
interface = gr.Interface(
    fn=predict_image,
    inputs=gr.Image(type="pil", label="Upload MRI Scan"),
    outputs=gr.Label(num_top_classes=2, label="AI Verdict"),
    title="🛡️ EPICS Deepfake MRI Detector",
    description="Upload a brain tumor MRI scan. Our custom EfficientNet AI will analyze the digital signatures and pixel patterns to determine if it is a genuine medical scan or a GAN-generated deepfake.",
    theme="default"
)

# 5. Launch the Web App!
# share=True creates a temporary public URL you can share with anyone
interface.launch(share=True, debug=True)

"""Gradio2.0"""

import gradio as gr
import torch
import torch.nn as nn
from torchvision import models, transforms
from PIL import Image
import torch.nn.functional as F
import numpy as np
import cv2
import os

# ==========================================
# 1. Setup & Architecture Definitions
# ==========================================
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print("Waking up the EPICS AI Pipeline...")

class Generator(nn.Module):
    def __init__(self, nz=100, ngf=64, nc=3):
        super(Generator, self).__init__()
        self.main = nn.Sequential(
            nn.ConvTranspose2d(nz, ngf * 8, 4, 1, 0, bias=False),
            nn.BatchNorm2d(ngf * 8),
            nn.ReLU(True),
            nn.ConvTranspose2d(ngf * 8, ngf * 4, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ngf * 4),
            nn.ReLU(True),
            nn.ConvTranspose2d(ngf * 4, ngf * 2, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ngf * 2),
            nn.ReLU(True),
            nn.ConvTranspose2d(ngf * 2, ngf, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ngf),
            nn.ReLU(True),
            nn.ConvTranspose2d(ngf, nc, 4, 2, 1, bias=False),
            nn.Tanh()
        )
    def forward(self, input):
        return self.main(input)

# ==========================================
# 2. Load the Detectors
# ==========================================
orientation_classes = ['axial', 'coronal', 'sagitall']
deepfake_classes = ['fake', 'real']

print("Loading Orientation Model...")
model_orient = models.resnet18(weights=None)
model_orient.fc = nn.Linear(model_orient.fc.in_features, len(orientation_classes))
model_orient.load_state_dict(torch.load('/content/drive/MyDrive/EPICS/mri_orientation_model.pth', map_location=device))
model_orient = model_orient.to(device)
model_orient.eval()

print("Loading Deepfake Detector...")
model_detect = models.efficientnet_b0(weights=None)
model_detect.classifier[1] = nn.Linear(model_detect.classifier[1].in_features, len(deepfake_classes))
model_detect.load_state_dict(torch.load('/content/drive/MyDrive/EPICS/deepfake_detector_efficientnet.pth', map_location=device))
model_detect = model_detect.to(device)
model_detect.eval()

# ==========================================
# 3. Vision Transforms & Helpers
# ==========================================
vision_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

to_pil = transforms.ToPILImage()

# NEW: Helper function for the rotate button
def rotate_image(img):
    if img is None:
        return None
    # Transpose rotates 90 degrees clockwise (270 degrees counter-clockwise)
    return img.transpose(Image.ROTATE_270)

# ==========================================
# 4. The Master Pipeline Function
# ==========================================
def process_mri(img):
    if img is None:
        return None, "No image provided.", None

    # STEP 1: Format & Convert
    img = img.convert('RGB')

    # [Automatic Rotation Removed - Now handled by the UI button!]

    # STEP 2: Intensity Filtering (Dark vs Bright)
    img_cv = np.array(img.convert('L'))
    mask = img_cv > 10
    mean_intensity = np.mean(img_cv[mask]) if np.any(mask) else 0
    contrast_label = "T1_Dark" if mean_intensity < 65 else "FLAIR_Bright"

    # STEP 3: Resize Bottleneck (64x64)
    img_bottleneck = img.resize((64, 64), Image.Resampling.LANCZOS)
    img_tensor = vision_transform(img_bottleneck).unsqueeze(0).to(device)

    with torch.no_grad():
        # STEP 4: Orientation Classification
        orient_out = model_orient(img_tensor)
        orient_idx = torch.argmax(orient_out, 1).item()
        plane_label = orientation_classes[orient_idx]

        # STEP 5: Deepfake Detection
        detect_out = model_detect(img_tensor)
        detect_probs = F.softmax(detect_out, dim=1)[0]

    verdict_dict = {deepfake_classes[i].upper(): float(detect_probs[i]) for i in range(len(deepfake_classes))}

    pipeline_report = (
        f"🔍 SEQUENCE ANALYSIS: {contrast_label} (Mean Brightness: {mean_intensity:.1f})\n"
        f"🧭 ORIENTATION PREDICTION: {plane_label.capitalize()}\n"
        f"📏 PIPELINE BOTTLENECK: Resized to 64x64 -> Upscaled to 224x224"
    )

    # STEP 6: Generate a "Synthetic Twin"
    gan_path_map = {
        "T1_Dark_axial": "/content/drive/MyDrive/EPICS/gen_T1_dark_axial.pth",
        "T1_Dark_coronal": "/content/drive/MyDrive/EPICS/gen_T1_dark_coronal.pth",
        "T1_Dark_sagitall": "/content/drive/MyDrive/EPICS/gen_T1_dark_sagitall.pth",
        "FLAIR_Bright_axial": "/content/drive/MyDrive/EPICS/gen_FLAIR_bright_axial.pth",
        "FLAIR_Bright_coronal": "/content/drive/MyDrive/EPICS/gen_FLAIR_bright_coronal.pth",
        "FLAIR_Bright_sagitall": "/content/drive/MyDrive/EPICS/gen_FLAIR_bright_sagitall.pth"
    }

    gan_key = f"{contrast_label}_{plane_label}"
    gan_weights_path = gan_path_map.get(gan_key)

    synthetic_twin_img = None
    if gan_weights_path and os.path.exists(gan_weights_path):
        netG = Generator().to(device)
        netG.load_state_dict(torch.load(gan_weights_path, map_location=device))
        netG.eval()

        with torch.no_grad():
            noise = torch.randn(1, 100, 1, 1, device=device)
            fake_tensor = netG(noise)
            fake_tensor = (fake_tensor.squeeze(0) + 1) / 2.0
            synthetic_twin_img = to_pil(fake_tensor.cpu())
            synthetic_twin_img = synthetic_twin_img.resize((256, 256), Image.Resampling.NEAREST)

        del netG
    else:
        pipeline_report += f"\n⚠️ Warning: Could not find GAN weights at {gan_weights_path}"

    return verdict_dict, pipeline_report, synthetic_twin_img

# ==========================================
# 5. Build the UI
# ==========================================
with gr.Blocks(theme=gr.themes.Soft()) as interface:
    gr.Markdown("# 🛡️ EPICS Comprehensive Deepfake MRI Pipeline")
    gr.Markdown("Upload a raw MRI scan. Use the rotate button to correct orientation if needed. The system will process it, determine its biological parameters, scan it for AI tampering, and generate a synthetic clone of that specific brain region.")

    with gr.Row():
        with gr.Column():
            input_img = gr.Image(type="pil", label="1. Upload MRI Scan")

            # NEW: The Rotate Button
            rotate_btn = gr.Button("↻ Rotate Image 90°")

            submit_btn = gr.Button("Initialize AI Pipeline", variant="primary")

        with gr.Column():
            out_verdict = gr.Label(num_top_classes=2, label="2. Deepfake Detector Verdict")
            out_report = gr.Textbox(label="3. Preprocessing Metadata", lines=3)
            out_twin = gr.Image(type="pil", label="4. Synthetic Twin (Generated by GAN)")

    # NEW: Wire the rotate button to instantly update the input image
    rotate_btn.click(
        fn=rotate_image,
        inputs=input_img,
        outputs=input_img
    )

    submit_btn.click(
        fn=process_mri,
        inputs=input_img,
        outputs=[out_verdict, out_report, out_twin]
    )

interface.launch(share=True, debug=True)