# -*- coding: utf-8 -*-
"""Final_Multi_Disease_Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r90_hQSwF7GhUJUozIvY2CVt7aGJt3Sj
"""

from google.colab import drive
drive.mount('/content/drive')

"""Understanding Checking"""

import torch
from torchvision import datasets, transforms
from torch.utils.data import DataLoader, random_split
import os

# 1. Setup Device
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(f"Detective Agency running on: {device}")

# 2. Path to your new Master Dataset
data_dir = '/content/drive/MyDrive/EPICS/lung_detector_dataset'

# 3. The Translator (Transforms)
# We are resizing everything to 224x224 because that is the exact size
# EfficientNet expects for optimal performance!
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# 4. Load the Data using ImageFolder Magic
full_dataset = datasets.ImageFolder(root=data_dir, transform=transform)

# Let's see what PyTorch found!
print("\n🔍 Dataset Scan Complete:")
print(f"Total images found: {len(full_dataset)}")
print(f"Classes detected: {full_dataset.classes}")
print(f"Class to Index mapping: {full_dataset.class_to_idx}")

# 5. Split into Training and Testing
# We keep 20% of the images hidden from the AI to test it like a final exam
train_size = int(0.8 * len(full_dataset))
test_size = len(full_dataset) - train_size
train_dataset, test_dataset = random_split(full_dataset, [train_size, test_size])

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True, num_workers=2)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False, num_workers=2)

print(f"\n📦 Training on {train_size} images.")
print(f"🧪 Testing on {test_size} images.")

"""Custom Built Classifier"""

import torch.nn as nn
import torch.nn.functional as F

class DeepfakeForensicsNet(nn.Module):
    def __init__(self):
        super(DeepfakeForensicsNet, self).__init__()

        # BLOCK 1: The Macro Scanner (Width: 32, Kernel: 3x3)
        self.conv1 = nn.Conv2d(in_channels=3, out_channels=32, kernel_size=3, padding=1)
        self.bn1 = nn.BatchNorm2d(32)
        self.pool1 = nn.MaxPool2d(kernel_size=2, stride=2)

        # BLOCK 2: The Texture Scanner (Width: 64, Kernel: 3x3)
        self.conv2 = nn.Conv2d(in_channels=32, out_channels=64, kernel_size=3, padding=1)
        self.bn2 = nn.BatchNorm2d(64)
        self.pool2 = nn.MaxPool2d(kernel_size=2, stride=2)

        # BLOCK 3: The Micro Scanner (Width: 128, Kernel: 3x3)
        self.conv3 = nn.Conv2d(in_channels=64, out_channels=128, kernel_size=3, padding=1)
        self.bn3 = nn.BatchNorm2d(128)
        self.pool3 = nn.MaxPool2d(kernel_size=2, stride=2)

        # BLOCK 4: The Deep Forensic Layer (Width: 256, Kernel: 3x3)
        self.conv4 = nn.Conv2d(in_channels=128, out_channels=256, kernel_size=3, padding=1)
        self.bn4 = nn.BatchNorm2d(256)
        self.pool4 = nn.MaxPool2d(kernel_size=2, stride=2)

        # THE JUDGE: Fully Connected Classification Layers
        # 256 filters * 14x14 remaining grid size
        self.fc1 = nn.Linear(256 * 14 * 14, 512)
        self.dropout = nn.Dropout(0.5) # The 50% Memorization Shield
        self.fc2 = nn.Linear(512, 2)   # Final Output: Fake (0) or Real (1)

    def forward(self, x):
        x = self.pool1(F.relu(self.bn1(self.conv1(x))))
        x = self.pool2(F.relu(self.bn2(self.conv2(x))))
        x = self.pool3(F.relu(self.bn3(self.conv3(x))))
        x = self.pool4(F.relu(self.bn4(self.conv4(x))))

        x = x.view(-1, 256 * 14 * 14) # Flatten for the Judge

        x = F.relu(self.fc1(x))
        x = self.dropout(x)
        x = self.fc2(x)
        return x

import torch
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

# Now it knows what 'device' is!
model = DeepfakeForensicsNet().to(device)
print("✅ Heavyweight DeepfakeForensicsNet (4-Block, 3x3 Kernel, 0.5 Dropout) ready for training!")

"""Data Loader"""

import torch
from torchvision import datasets, transforms
from torch.utils.data import DataLoader, random_split

# 1. Point to your Master Dataset
data_dir = '/content/drive/MyDrive/EPICS/lung_detector_dataset'

# 2. Set up the Image Translator
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# 3. Load and Split the Data
print("🔍 Scanning Google Drive for images...")
full_dataset = datasets.ImageFolder(root=data_dir, transform=transform)

train_size = int(0.8 * len(full_dataset))
test_size = len(full_dataset) - train_size
train_dataset, test_dataset = random_split(full_dataset, [train_size, test_size])

# 4. Create the Loaders! (This is what fixes your exact error)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True, num_workers=2)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False, num_workers=2)

print(f"✅ Success! 'train_loader' is officially defined and packed with {train_size} images.")

"""Training Loop Code"""

import torch.optim as optim

# ==========================================
# 1. The Grader and The Updater
# ==========================================
# CrossEntropyLoss is the standard grader for "Multiple Choice" or "True/False" AI
criterion = nn.CrossEntropyLoss()

# Adam is the optimizer. It updates the 256 filters based on the Grader's feedback.
# lr=0.001 is the "Learning Rate" (how fast it changes its mind).
optimizer = optim.Adam(model.parameters(), lr=0.001)

num_epochs = 15

# ==========================================
# 2. The 15-Epoch Marathon
# ==========================================
print(f"🚀 Booting up the Training Facility for {num_epochs} Epochs...")

for epoch in range(num_epochs):
    model.train() # CRITICAL: This turns ON your 50% Dropout shield!

    running_loss = 0.0
    correct_guesses = 0
    total_images = 0

    # Pass the images through the network in batches of 32
    for images, labels in train_loader:
        # Send the images and the answer key to the GPU
        images, labels = images.to(device), labels.to(device)

        # 1. Clear the whiteboard
        optimizer.zero_grad()

        # 2. Make a Guess (Forward Pass)
        outputs = model(images)
        loss = criterion(outputs, labels)

        # 3. Learn from Mistakes (Backward Pass)
        loss.backward()
        optimizer.step()

        # 4. Calculate Accuracy for this batch
        running_loss += loss.item()
        _, predicted = torch.max(outputs.data, 1)
        total_images += labels.size(0)
        correct_guesses += (predicted == labels).sum().item()

    # Print the report card at the end of every epoch
    epoch_acc = 100 * correct_guesses / total_images
    epoch_loss = running_loss / len(train_loader)
    print(f"Epoch [{epoch+1}/{num_epochs}] | Loss: {epoch_loss:.4f} | Training Accuracy: {epoch_acc:.2f}%")

print("\n🎓 Graduation Day! Your custom AI is fully educated.")

# ==========================================
# 3. Save the Masterpiece
# ==========================================
save_path = '/content/drive/MyDrive/EPICS/custom_lung_detector.pth'
torch.save(model.state_dict(), save_path)
print(f"💾 Success! Saved your final weights to: {save_path}")

"""Tester"""

import torch

# ==========================================
# 1. THE EXAM PREP
# ==========================================
# CRITICAL: This line turns OFF your 50% Dropout shield!
# The AI is now allowed to use 100% of its 256-filter brain.
model.eval()

print("🕵️‍♂️ Locking weights and initiating the Final Exam on unseen data...")

correct_guesses = 0
total_images = 0

# ==========================================
# 2. THE FINAL EXAM
# ==========================================
# torch.no_grad() tells PyTorch to stop tracking math for "learning".
# The AI is no longer a student; it is now a pure Judge.
with torch.no_grad():
    for images, labels in test_loader:
        # Send data to the GPU
        images, labels = images.to(device), labels.to(device)

        # The AI makes its guess
        outputs = model(images)

        # We grab the highest probability guess (0 for FAKE, 1 for REAL)
        _, predicted = torch.max(outputs.data, 1)

        # Tally up the final score
        total_images += labels.size(0)
        correct_guesses += (predicted == labels).sum().item()

# ==========================================
# 3. THE REPORT CARD
# ==========================================
final_accuracy = 100 * correct_guesses / total_images

print("\n" + "="*40)
print(f"🎯 FINAL EXAM SCORE: {final_accuracy:.2f}%")
print(f"🧠 Total Images Scanned: {total_images}")
print(f"✅ Correctly Classified: {correct_guesses}")
print(f"❌ Missed: {total_images - correct_guesses}")
print("="*40)

"""Tester"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import transforms
from PIL import Image

# ==========================================
# 1. Setup Device and Classes
# ==========================================
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
class_names = ['FAKE', 'REAL'] # Index 0 = Fake, Index 1 = Real

# ==========================================
# 2. Rebuild the Architecture (The Custom Blueprint)
# ==========================================
class DeepfakeForensicsNet(nn.Module):
    def __init__(self):
        super(DeepfakeForensicsNet, self).__init__()
        self.conv1 = nn.Conv2d(3, 32, 3, padding=1)
        self.bn1 = nn.BatchNorm2d(32)
        self.pool1 = nn.MaxPool2d(2, 2)

        self.conv2 = nn.Conv2d(32, 64, 3, padding=1)
        self.bn2 = nn.BatchNorm2d(64)
        self.pool2 = nn.MaxPool2d(2, 2)

        self.conv3 = nn.Conv2d(64, 128, 3, padding=1)
        self.bn3 = nn.BatchNorm2d(128)
        self.pool3 = nn.MaxPool2d(2, 2)

        self.conv4 = nn.Conv2d(128, 256, 3, padding=1)
        self.bn4 = nn.BatchNorm2d(256)
        self.pool4 = nn.MaxPool2d(2, 2)

        self.fc1 = nn.Linear(256 * 14 * 14, 512)
        self.dropout = nn.Dropout(0.5)
        self.fc2 = nn.Linear(512, 2)

    def forward(self, x):
        x = self.pool1(F.relu(self.bn1(self.conv1(x))))
        x = self.pool2(F.relu(self.bn2(self.conv2(x))))
        x = self.pool3(F.relu(self.bn3(self.conv3(x))))
        x = self.pool4(F.relu(self.bn4(self.conv4(x))))
        x = x.view(-1, 256 * 14 * 14)
        x = F.relu(self.fc1(x))
        x = self.dropout(x)
        x = self.fc2(x)
        return x

# ==========================================
# 3. Load Your Masterpiece
# ==========================================
print("Waking up the Lung Deepfake Detector...")
model = DeepfakeForensicsNet()
model_path = '/content/drive/MyDrive/EPICS/custom_lung_detector.pth'

# Load the weights into your custom architecture
model.load_state_dict(torch.load(model_path, map_location=device))
model = model.to(device)
model.eval() # CRITICAL: Set to prediction mode (Turns off the Dropout layer)

# ==========================================
# 4. Define the Vision Transforms
# ==========================================
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

# ==========================================
# 5. The Prediction Engine
# ==========================================
def scan_lung_for_deepfakes(image_path):
    try:
        # Open and format the image
        img = Image.open(image_path).convert('RGB')
        img_tensor = transform(img).unsqueeze(0).to(device)

        # Make the prediction
        with torch.no_grad():
            outputs = model(img_tensor)

            # Convert the raw math into readable percentages using Softmax
            probabilities = F.softmax(outputs, dim=1)[0]
            confidence, predicted_idx = torch.max(probabilities, 0)

        predicted_class = class_names[predicted_idx.item()]
        confidence_pct = confidence.item() * 100

        print(f"\nScan Complete for: {image_path.split('/')[-1]}")
        print("-" * 30)
        print(f"Verdict:    {predicted_class}")
        print(f"Confidence: {confidence_pct:.2f}%")

    except Exception as e:
        print(f"Error scanning image: {e}")

# ==========================================
# 6. TEST IT HERE
# ==========================================
# Update this string to point to ANY specific image in your Drive
test_image_path = '/content/drive/MyDrive/EPICS/lung_detector_dataset/FAKE/synthetic_pneumonia_10.jpg'

scan_lung_for_deepfakes(test_image_path)

"""gradio"""

pip install gradio

import gradio as gr
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import transforms, models
from PIL import Image

# ==========================================
# 1. SETUP HARDWARE & CONSTANTS
# ==========================================
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
class_names = ['FAKE', 'REAL'] # Index 0 = Fake, Index 1 = Real

# ==========================================
# 2. DEFINE LUNG ARCHITECTURE (Custom CNN)
# ==========================================
class DeepfakeForensicsNet(nn.Module):
    def __init__(self):
        super(DeepfakeForensicsNet, self).__init__()
        self.conv1 = nn.Conv2d(3, 32, 3, padding=1)
        self.bn1 = nn.BatchNorm2d(32)
        self.pool1 = nn.MaxPool2d(2, 2)

        self.conv2 = nn.Conv2d(32, 64, 3, padding=1)
        self.bn2 = nn.BatchNorm2d(64)
        self.pool2 = nn.MaxPool2d(2, 2)

        self.conv3 = nn.Conv2d(64, 128, 3, padding=1)
        self.bn3 = nn.BatchNorm2d(128)
        self.pool3 = nn.MaxPool2d(2, 2)

        self.conv4 = nn.Conv2d(128, 256, 3, padding=1)
        self.bn4 = nn.BatchNorm2d(256)
        self.pool4 = nn.MaxPool2d(2, 2)

        self.fc1 = nn.Linear(256 * 14 * 14, 512)
        self.dropout = nn.Dropout(0.5)
        self.fc2 = nn.Linear(512, 2)

    def forward(self, x):
        x = self.pool1(F.relu(self.bn1(self.conv1(x))))
        x = self.pool2(F.relu(self.bn2(self.conv2(x))))
        x = self.pool3(F.relu(self.bn3(self.conv3(x))))
        x = self.pool4(F.relu(self.bn4(self.conv4(x))))
        x = x.view(-1, 256 * 14 * 14)
        x = F.relu(self.fc1(x))
        x = self.dropout(x)
        x = self.fc2(x)
        return x

# ==========================================
# 3. INITIALIZE & LOAD MODELS
# ==========================================
# A. Load Lung Specialist
lung_model = DeepfakeForensicsNet().to(device)
lung_path = '/content/drive/MyDrive/EPICS/custom_lung_detector.pth'

try:
    lung_model.load_state_dict(torch.load(lung_path, map_location=device))
    lung_model.eval()
    print("✅ Lung Specialist Weights Loaded.")
except Exception as e:
    print(f"⚠️ Error loading Lung model: {e}")

# B. Load Brain Specialist (EfficientNet-B0)
brain_model = models.efficientnet_b0(weights=None)
num_ftrs = brain_model.classifier[1].in_features
brain_model.classifier[1] = nn.Linear(num_ftrs, len(class_names))
brain_path = '/content/drive/MyDrive/EPICS/deepfake_detector_efficientnet.pth'

try:
    brain_model.load_state_dict(torch.load(brain_path, map_location=device))
    brain_model = brain_model.to(device)
    brain_model.eval()
    print("✅ Brain Specialist Weights Loaded.")
except Exception as e:
    print(f"⚠️ Error loading Brain model: {e}")

# ==========================================
# 4. PREPROCESSING & ANALYSIS ENGINE
# ==========================================
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

def forensic_analysis(image, organ_type):
    if image is None:
        return "⚠️ Please upload an image to begin analysis."

    # Preprocess image
    img_tensor = transform(image).unsqueeze(0).to(device)

    # Route to the correct Specialist
    target_model = lung_model if organ_type == "Lungs (X-Ray)" else brain_model

    with torch.no_grad():
        outputs = target_model(img_tensor)
        probabilities = F.softmax(outputs, dim=1)[0]
        confidence, predicted_idx = torch.max(probabilities, 0)

    result = class_names[predicted_idx.item()]
    confidence_pct = confidence.item() * 100

    # Dynamic Styling based on Result
    if result == "REAL":
        return f"🟢 VERDICT: AUTHENTIC SCAN\n\nOrgan Analyzed: {organ_type}\nForensic Confidence: {confidence_pct:.2f}%\nStatus: Zero algorithmic fingerprints detected."
    else:
        return f"🔴 VERDICT: FORGERY DETECTED (DEEPFAKE)\n\nOrgan Analyzed: {organ_type}\nForensic Confidence: {confidence_pct:.2f}%\nStatus: GAN-generated upscaling artifacts identified."

# ==========================================
# 5. GRADIO USER INTERFACE
# ==========================================
with gr.Blocks(theme=gr.themes.Base()) as demo:
    gr.Markdown("<h1 style='text-align: center;'>🩺 Multi-Disease Medical Deepfake Detector</h1>")
    gr.Markdown("<p style='text-align: center;'>A unified forensic platform to identify GAN-generated forgeries in X-Ray and MRI data.</p>")

    with gr.Row():
        # LEFT COLUMN: User Input
        with gr.Column():
            organ_input = gr.Dropdown(
                choices=["Lungs (X-Ray)", "Brain (MRI)"],
                label="1. Choose Target Organ",
                value="Lungs (X-Ray)"
            )
            image_input = gr.Image(type="pil", label="2. Upload Medical Scan")
            run_btn = gr.Button("🔍 Run Forensic Scan", variant="primary")

        # RIGHT COLUMN: Clinical Report
        with gr.Column():
            output_report = gr.Textbox(
                label="3. Analysis Report",
                lines=8,
                placeholder="The clinical report will appear here after the scan..."
            )

    # Action Trigger
    run_btn.click(
        fn=forensic_analysis,
        inputs=[image_input, organ_input],
        outputs=output_report
    )

# Launch with a public shareable link
demo.launch(share=True)