# -*- coding: utf-8 -*-
"""lungdetectionGANtrainer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xzICsDin-Tlmo-VtaVqz0Bk6QJLAE0aI
"""

from google.colab import drive
drive.mount('/content/drive')

"""Extracting Files"""

import zipfile
import os

# 1. Point this to the ZIP file you just uploaded
zip_path = '/content/drive/MyDrive/EPICS/pneumonia_dataset/archive (7).zip'

# 2. Point this to where you want the images to go
extract_path = '/content/drive/MyDrive/EPICS/pneumonia_dataset/real'

# 3. Create the target folder if it doesn't exist
os.makedirs(extract_path, exist_ok=True)

# 4. Extract everything!
print("Extracting X-rays. This might take a minute...")
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print(f"✅ Success! All X-rays extracted to: {extract_path}")

"""Reorganizing Images"""

import os
import shutil

# 1. Where the messy extracted files currently are
messy_base_dir = '/content/drive/MyDrive/EPICS/pneumonia_dataset/real'

# 2. Where we want the clean, combined files to go
clean_pneumonia_dir = '/content/drive/MyDrive/EPICS/pneumonia_dataset/clean_pneumonia'
clean_normal_dir = '/content/drive/MyDrive/EPICS/pneumonia_dataset/clean_normal'

os.makedirs(clean_pneumonia_dir, exist_ok=True)
os.makedirs(clean_normal_dir, exist_ok=True)

pneumonia_count = 0
normal_count = 0

print("Vacuuming up the X-rays... Ignore the Mac junk!")

# 3. Walk through every single folder and subfolder
for root, dirs, files in os.walk(messy_base_dir):

    # Skip the annoying Mac junk folders entirely
    if '__MACOSX' in root:
        continue

    for file in files:
        # Skip invisible Mac files
        if file.startswith('._') or file == '.DS_Store':
            continue

        # If it's a valid image...
        if file.lower().endswith(('.png', '.jpeg', '.jpg')):
            file_path = os.path.join(root, file)

            # Check if the folder it came from says "PNEUMONIA"
            if 'PNEUMONIA' in root.upper():
                # Move it to our clean pneumonia folder
                # We add the count to the filename so files with the same name don't overwrite each other
                new_name = f"pneumonia_{pneumonia_count}.jpeg"
                shutil.move(file_path, os.path.join(clean_pneumonia_dir, new_name))
                pneumonia_count += 1

            # Check if the folder it came from says "NORMAL"
            elif 'NORMAL' in root.upper():
                new_name = f"normal_{normal_count}.jpeg"
                shutil.move(file_path, os.path.join(clean_normal_dir, new_name))
                normal_count += 1

print("\n✅ Cleanup complete!")
print(f"Successfully rescued {pneumonia_count} Pneumonia X-rays into: {clean_pneumonia_dir}")
print(f"Successfully rescued {normal_count} Normal X-rays into: {clean_normal_dir}")

import os
import shutil

# 1. Define our paths
base_dir = '/content/drive/MyDrive/EPICS/pneumonia_dataset'
messy_extracted_dir = os.path.join(base_dir, 'real') # Where the zip dumped everything
clean_pneumonia = os.path.join(base_dir, 'clean_pneumonia')
clean_normal = os.path.join(base_dir, 'clean_normal')

os.makedirs(clean_pneumonia, exist_ok=True)
os.makedirs(clean_normal, exist_ok=True)

print("Searching through train/test/val folders to consolidate images...")

pn_count = 0
nm_count = 0

# 2. Move all the files out of the nested folders
for root, dirs, files in os.walk(messy_extracted_dir):
    # Ignore Mac junk
    if '__MACOSX' in root: continue

    for file in files:
        if file.lower().endswith(('.png', '.jpeg', '.jpg')):
            old_path = os.path.join(root, file)

            # Route to the correct master folder
            if 'PNEUMONIA' in root.upper():
                new_path = os.path.join(clean_pneumonia, f"pneum_master_{pn_count}.jpeg")
                shutil.move(old_path, new_path)
                pn_count += 1

            elif 'NORMAL' in root.upper():
                new_path = os.path.join(clean_normal, f"norm_master_{nm_count}.jpeg")
                shutil.move(old_path, new_path)
                nm_count += 1

print(f"✅ Gathered {pn_count} Pneumonia X-rays.")
print(f"✅ Gathered {nm_count} Normal X-rays.")

# 3. Destroy the old, confusing nested folders
print("Deleting the old train/test/val folders to clean up your Drive...")
try:
    shutil.rmtree(messy_extracted_dir)
    print("✅ Drive cleanup complete!")
except Exception as e:
    print(f"Could not delete old folders automatically, but files are safely moved! Error: {e}")

print(f"\nYour images are now waiting in: {clean_pneumonia}")

import os
import shutil

# 1. Define paths
base_dir = '/content/drive/MyDrive/EPICS/pneumonia_dataset'
messy_dir = os.path.join(base_dir, 'real')
clean_pn = os.path.join(base_dir, 'clean_pneumonia')
clean_nm = os.path.join(base_dir, 'clean_normal')

# Force create the clean folders
os.makedirs(clean_pn, exist_ok=True)
os.makedirs(clean_nm, exist_ok=True)

pn_count = 0
nm_count = 0

print(f"Scanning deeply inside: {messy_dir} ...\n")

# 2. Walk through every single folder recursively
for root, dirs, files in os.walk(messy_dir):
    # Completely ignore the Mac junk
    if '__MACOSX' in root:
        continue

    for file in files:
        if file.lower().endswith(('.jpeg', '.jpg', '.png')):
            source_path = os.path.join(root, file)

            # Check if it belongs in Pneumonia
            if 'PNEUMONIA' in root.upper():
                dest_path = os.path.join(clean_pn, f"pneumonia_{pn_count}.jpeg")
                # Using COPY instead of MOVE for absolute safety
                if not os.path.exists(dest_path):
                    shutil.copy2(source_path, dest_path)
                pn_count += 1

            # Check if it belongs in Normal
            elif 'NORMAL' in root.upper():
                dest_path = os.path.join(clean_nm, f"normal_{nm_count}.jpeg")
                if not os.path.exists(dest_path):
                    shutil.copy2(source_path, dest_path)
                nm_count += 1

print(f"✅ Successfully copied {pn_count} PNEUMONIA images.")
print(f"✅ Successfully copied {nm_count} NORMAL images.")
print(f"They are safely stored in:\n- {clean_pn}\n- {clean_nm}")

"""Resizing Images"""

import os
from PIL import Image

# 1. Define our Base Paths
base_dir = '/content/drive/MyDrive/EPICS/pneumonia_dataset'

# Input folders (your beautifully clean folders)
input_pn = os.path.join(base_dir, 'clean_pneumonia')
input_nm = os.path.join(base_dir, 'clean_normal')

# Output folders (where the 256x256 images will live)
output_pn = os.path.join(base_dir, 'pneumonia_256x256')
output_nm = os.path.join(base_dir, 'normal_256x256')

# Create the output folders
os.makedirs(output_pn, exist_ok=True)
os.makedirs(output_nm, exist_ok=True)

# 2. The Resizing Engine
def batch_resize(input_folder, output_folder, class_name):
    print(f"\n🚀 Starting batch resize for {class_name}...")

    if not os.path.exists(input_folder):
        print(f"⚠️ Error: Could not find {input_folder}")
        return

    processed_count = 0
    valid_extensions = ('.jpg', '.jpeg', '.png')

    for filename in os.listdir(input_folder):
        if filename.lower().endswith(valid_extensions):
            img_path = os.path.join(input_folder, filename)
            out_path = os.path.join(output_folder, filename)

            # Skip if already processed (this is great if Colab ever crashes and you need to restart!)
            if os.path.exists(out_path):
                processed_count += 1
                continue

            try:
                with Image.open(img_path) as img:
                    # Convert to standard RGB to prevent channel errors in PyTorch
                    img = img.convert('RGB')

                    # Resize to exactly 256x256 using the highest quality filter (LANCZOS)
                    resized_img = img.resize((256, 256), Image.Resampling.LANCZOS)

                    # Save the image
                    resized_img.save(out_path)

                    processed_count += 1

                    # Print progress every 500 images so you know it hasn't frozen
                    if processed_count % 500 == 0:
                        print(f"Resized {processed_count} {class_name} images...")

            except Exception as e:
                print(f"⚠️ Could not process {filename}: {e}")

    print(f"✅ Success! Resized {processed_count} {class_name} images to 256x256.")

# 3. Execute the process for both classes
batch_resize(input_pn, output_pn, "PNEUMONIA")
batch_resize(input_nm, output_nm, "NORMAL")

print(f"\n🎉 ALL DONE! Your optimized datasets are ready at:")
print(f"- {output_pn}")
print(f"- {output_nm}")

"""Organizing Images"""

import os
import shutil

# 1. Define paths
base_dir = '/content/drive/MyDrive/EPICS/pneumonia_dataset'
messy_dir = os.path.join(base_dir, 'real')

# The exact X-ray categories
clean_normal = os.path.join(base_dir, 'normal_xrays')
clean_bacteria = os.path.join(base_dir, 'pneumonia_bacteria_xrays')
clean_virus = os.path.join(base_dir, 'pneumonia_virus_xrays')

print("Setting up specific X-ray category folders...")

# Clean up any old mistakes from previous runs to prevent duplicates
for folder in [clean_normal, clean_bacteria, clean_virus, os.path.join(base_dir, 'clean_pneumonia'), os.path.join(base_dir, 'clean_normal')]:
    if os.path.exists(folder):
        shutil.rmtree(folder)

# Create the new specific folders
os.makedirs(clean_normal, exist_ok=True)
os.makedirs(clean_bacteria, exist_ok=True)
os.makedirs(clean_virus, exist_ok=True)

norm_count = 0
bact_count = 0
vir_count = 0

print("Scanning file signatures for Bacteria vs Virus...\n")

# 2. The Sorting Engine
for root, dirs, files in os.walk(messy_dir):
    # Ignore Mac junk
    if '__MACOSX' in root: continue

    for file in files:
        if file.lower().endswith(('.jpeg', '.jpg', '.png')):
            source_path = os.path.join(root, file)
            parent_folder = os.path.basename(root).upper()
            filename_lower = file.lower()

            # NORMAL X-RAYS
            if 'NORMAL' in parent_folder:
                dest_path = os.path.join(clean_normal, f"normal_{norm_count}.jpeg")
                shutil.copy2(source_path, dest_path)
                norm_count += 1

            # PNEUMONIA X-RAYS (Split by Bacteria or Virus)
            elif 'PNEUMONIA' in parent_folder:
                # The file names actually tell us the disease type!
                if 'bacteria' in filename_lower:
                    dest_path = os.path.join(clean_bacteria, f"bacteria_{bact_count}.jpeg")
                    shutil.copy2(source_path, dest_path)
                    bact_count += 1

                elif 'virus' in filename_lower:
                    dest_path = os.path.join(clean_virus, f"virus_{vir_count}.jpeg")
                    shutil.copy2(source_path, dest_path)
                    vir_count += 1

print(f"✅ Separated {norm_count} NORMAL X-rays.")
print(f"✅ Separated {bact_count} BACTERIAL Pneumonia X-rays.")
print(f"✅ Separated {vir_count} VIRAL Pneumonia X-rays.")
print(f"\nYour X-rays are properly categorized and saved in Drive!")

import os
import shutil
import zipfile

# 1. Define paths
base_dir = '/content/drive/MyDrive/EPICS/pneumonia_dataset'
zip_path = os.path.join(base_dir, 'archive (7).zip') # Based on your screenshot
messy_dir = os.path.join(base_dir, 'real_temp')

clean_normal = os.path.join(base_dir, 'normal_xrays')
clean_bacteria = os.path.join(base_dir, 'pneumonia_bacteria_xrays')
clean_virus = os.path.join(base_dir, 'pneumonia_virus_xrays')

print("Starting the Master Reset Pipeline...\n")

# STEP 1: Re-extract the original files to get the "bacteria" and "virus" names back
if not os.path.exists(messy_dir):
    print("📦 Extracting original ZIP file...")
    if os.path.exists(zip_path):
        os.makedirs(messy_dir, exist_ok=True)
        with zipfile.ZipFile(zip_path, 'r') as zip_ref:
            zip_ref.extractall(messy_dir)
        print("Extraction complete!\n")
    else:
        print("⚠️ ERROR: ZIP file not found! Please ensure 'archive (7).zip' is still in your folder.")

# STEP 2: Wipe the destination folders so we start perfectly fresh
for folder in [clean_normal, clean_bacteria, clean_virus]:
    if os.path.exists(folder):
        shutil.rmtree(folder)
    os.makedirs(folder, exist_ok=True)

print("🔍 Scanning file signatures for Bacteria vs Virus...")
norm_count = 0
bact_count = 0
vir_count = 0

# STEP 3: The Sorting Engine
for root, dirs, files in os.walk(messy_dir):
    if '__MACOSX' in root: continue

    for file in files:
        if file.lower().endswith(('.jpeg', '.jpg', '.png')):
            source_path = os.path.join(root, file)
            parent_folder = os.path.basename(root).upper()
            filename_lower = file.lower()

            # NORMAL X-RAYS
            if 'NORMAL' in parent_folder:
                dest_path = os.path.join(clean_normal, f"normal_{norm_count}.jpeg")
                shutil.copy2(source_path, dest_path)
                norm_count += 1

            # PNEUMONIA X-RAYS
            elif 'PNEUMONIA' in parent_folder:
                if 'bacteria' in filename_lower:
                    dest_path = os.path.join(clean_bacteria, f"bacteria_{bact_count}.jpeg")
                    shutil.copy2(source_path, dest_path)
                    bact_count += 1
                elif 'virus' in filename_lower:
                    dest_path = os.path.join(clean_virus, f"virus_{vir_count}.jpeg")
                    shutil.copy2(source_path, dest_path)
                    vir_count += 1

print(f"✅ Separated {norm_count} NORMAL X-rays.")
print(f"✅ Separated {bact_count} BACTERIAL Pneumonia X-rays.")
print(f"✅ Separated {vir_count} VIRAL Pneumonia X-rays.")

# Cleanup the temporary extraction folder to save Drive space
if os.path.exists(messy_dir):
    shutil.rmtree(messy_dir)

print("\n🎉 DONE! Your X-rays are perfectly categorized!")

"""GAN Training"""

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision.transforms as transforms
from torch.utils.data import Dataset, DataLoader
from PIL import Image
import os
import glob

# ==========================================
# 1. Configuration & Paths
# ==========================================
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(f"Training on: {device}")

# ---> THE MAGIC FIX: Tell the AI where to pick up from! <---
resume_epoch = 450  # Change this to 50, 100, 150, etc., based on your Drive files!
# (Set to 0 if you ever want to start completely from scratch)

data_folder = '/content/drive/MyDrive/EPICS/pneumonia_dataset/pneumonia_256x256'
save_model_path = '/content/drive/MyDrive/EPICS/gen_pneumonia.pth'

batch_size = 32
image_size = 64
nz = 100
num_epochs = 500
lr = 0.0001
beta1 = 0.5

# ==========================================
# 2. Custom Dataset Loader
# ==========================================
class SingleFolderDataset(Dataset):
    def __init__(self, folder_path, transform=None):
        self.image_paths = []
        for ext in ('*.jpg', '*.jpeg', '*.png'):
            self.image_paths.extend(glob.glob(os.path.join(folder_path, ext)))
            self.image_paths.extend(glob.glob(os.path.join(folder_path, ext.upper())))
        self.transform = transform

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        img_path = self.image_paths[idx]
        image = Image.open(img_path).convert('RGB')
        if self.transform:
            image = self.transform(image)
        return image, 0

transform = transforms.Compose([
    transforms.Resize(image_size),
    transforms.CenterCrop(image_size),
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)),
])

dataset = SingleFolderDataset(data_folder, transform=transform)
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True, num_workers=2)

# ==========================================
# 3. Neural Network Architectures
# ==========================================
class Generator(nn.Module):
    def __init__(self, nz=100, ngf=64, nc=3):
        super(Generator, self).__init__()
        self.main = nn.Sequential(
            nn.ConvTranspose2d(nz, ngf * 8, 4, 1, 0, bias=False),
            nn.BatchNorm2d(ngf * 8),
            nn.ReLU(True),
            nn.ConvTranspose2d(ngf * 8, ngf * 4, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ngf * 4),
            nn.ReLU(True),
            nn.ConvTranspose2d(ngf * 4, ngf * 2, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ngf * 2),
            nn.ReLU(True),
            nn.ConvTranspose2d(ngf * 2, ngf, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ngf),
            nn.ReLU(True),
            nn.ConvTranspose2d(ngf, nc, 4, 2, 1, bias=False),
            nn.Tanh()
        )
    def forward(self, input):
        return self.main(input)

class Discriminator(nn.Module):
    def __init__(self, nc=3, ndf=64):
        super(Discriminator, self).__init__()
        self.main = nn.Sequential(
            nn.Conv2d(nc, ndf, 4, 2, 1, bias=False),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Conv2d(ndf, ndf * 2, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ndf * 2),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Conv2d(ndf * 2, ndf * 4, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ndf * 4),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Conv2d(ndf * 4, ndf * 8, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ndf * 8),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Conv2d(ndf * 8, 1, 4, 1, 0, bias=False),
            nn.Sigmoid()
        )
    def forward(self, input):
        return self.main(input)

netG = Generator().to(device)
netD = Discriminator().to(device)

# ==========================================
# 3.5 THE RESUME MODULE (Curing the Amnesia)
# ==========================================
if resume_epoch > 0:
    checkpoint_path = f'/content/drive/MyDrive/EPICS/gen_pneumonia_epoch_{resume_epoch}.pth'
    if os.path.exists(checkpoint_path):
        print(f"\n🔄 WAKING UP AI: Loading Brain from Epoch {resume_epoch}...")
        netG.load_state_dict(torch.load(checkpoint_path, map_location=device))
        print(f"✅ Success! Resuming training from Epoch {resume_epoch}.")
    else:
        print(f"\n⚠️ ERROR: Could not find {checkpoint_path}. Did you type the number correctly?")
        print("Starting from scratch instead.")
        resume_epoch = 0
else:
    print("\n🌱 Starting training completely from scratch (Epoch 0).")

# ==========================================
# 4. Training Loop
# ==========================================
criterion = nn.BCELoss()
optimizerD = optim.Adam(netD.parameters(), lr=lr, betas=(beta1, 0.999))
optimizerG = optim.Adam(netG.parameters(), lr=lr, betas=(beta1, 0.999))

print("\n🚀 Training Initiated...")

# NOTE: The loop now starts at your resume_epoch instead of 0!
for epoch in range(resume_epoch, num_epochs):
    for i, data in enumerate(dataloader, 0):
        # Train Discriminator
        netD.zero_grad()
        real_cpu = data[0].to(device)
        b_size = real_cpu.size(0)

        label = torch.full((b_size,), 0.9, dtype=torch.float, device=device)
        output = netD(real_cpu).view(-1)
        errD_real = criterion(output, label)
        errD_real.backward()

        noise = torch.randn(b_size, nz, 1, 1, device=device)
        fake = netG(noise)
        label.fill_(0.0)
        output = netD(fake.detach()).view(-1)
        errD_fake = criterion(output, label)
        errD_fake.backward()

        errD = errD_real + errD_fake
        optimizerD.step()

        # Train Generator
        netG.zero_grad()
        label.fill_(0.9)
        output = netD(fake).view(-1)
        errG = criterion(output, label)
        errG.backward()
        optimizerG.step()

    # Save and Print Progress
    if (epoch + 1) % 50 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}] | Loss_D: {errD.item():.4f} | Loss_G: {errG.item():.4f}')
        checkpoint_name = f'/content/drive/MyDrive/EPICS/gen_pneumonia_epoch_{epoch+1}.pth'
        torch.save(netG.state_dict(), checkpoint_name)
        print(f"💾 Backup saved: {checkpoint_name}")

torch.save(netG.state_dict(), save_model_path)
print(f"\n✅ Success! Final GAN weights securely saved to: {save_model_path}")

"""Mass Production Code

"""

import torch
import torch.nn as nn
import torchvision.transforms as transforms
from torchvision.utils import save_image
import os
from tqdm import tqdm # This gives us a cool progress bar!

# ==========================================
# 1. Configuration & Paths
# ==========================================
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(f"Factory running on: {device}")

# Where the brain is, and where the fakes are going
model_path = '/content/drive/MyDrive/EPICS/gen_pneumonia.pth'
output_folder = '/content/drive/MyDrive/EPICS/pneumonia_dataset/fake_pneumonia'

# Create the new folder safely
os.makedirs(output_folder, exist_ok=True)

# Factory Settings
num_images_to_generate = 2000
batch_size = 64
nz = 100 # The size of the noise vector

# ==========================================
# 2. Rebuild the Brain (Generator Only!)
# ==========================================
class Generator(nn.Module):
    def __init__(self, nz=100, ngf=64, nc=3):
        super(Generator, self).__init__()
        self.main = nn.Sequential(
            nn.ConvTranspose2d(nz, ngf * 8, 4, 1, 0, bias=False),
            nn.BatchNorm2d(ngf * 8),
            nn.ReLU(True),
            nn.ConvTranspose2d(ngf * 8, ngf * 4, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ngf * 4),
            nn.ReLU(True),
            nn.ConvTranspose2d(ngf * 4, ngf * 2, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ngf * 2),
            nn.ReLU(True),
            nn.ConvTranspose2d(ngf * 2, ngf, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ngf),
            nn.ReLU(True),
            nn.ConvTranspose2d(ngf, nc, 4, 2, 1, bias=False),
            nn.Tanh()
        )
    def forward(self, input):
        return self.main(input)

# Load the graduated AI into memory
netG = Generator().to(device)
netG.load_state_dict(torch.load(model_path, map_location=device))
netG.eval() # CRITICAL: Locks the brain so it stops learning!

# We upscale the 64x64 output to 256x256 so it perfectly matches your Real X-rays
upscale = transforms.Resize((256, 256), antialias=True)

# ==========================================
# 3. The Assembly Line
# ==========================================
print(f"\n🏭 Starting Mass Production of {num_images_to_generate} Fake X-rays...")

with torch.no_grad(): # Turn off math tracking to save RAM and run 10x faster

    images_generated = 0
    pbar = tqdm(total=num_images_to_generate, desc="Forging Images")

    while images_generated < num_images_to_generate:
        # Calculate how many to make in this batch
        current_batch_size = min(batch_size, num_images_to_generate - images_generated)

        # 1. Create pure digital static (noise)
        noise = torch.randn(current_batch_size, nz, 1, 1, device=device)

        # 2. Feed static to the Generator to sculpt the fake X-ray
        fake_images = netG(noise)

        # 3. Upscale them to 256x256
        fake_images = upscale(fake_images)

        # 4. Save them one by one to your Drive
        for i in range(current_batch_size):
            image_tensor = fake_images[i]

            # The GAN outputs colors from -1 to 1. We shift it to 0 to 1 for standard images.
            image_tensor = (image_tensor + 1) / 2.0

            # Save the file
            file_name = os.path.join(output_folder, f"synthetic_pneumonia_{images_generated + i + 1}.jpg")
            save_image(image_tensor, file_name)

        images_generated += current_batch_size
        pbar.update(current_batch_size)

print(f"\n✅ Production Complete! {num_images_to_generate} Master Forgeries saved to your Google Drive.")

"""Image Reorganizer"""

import os
import shutil
from tqdm import tqdm

# ==========================================
# 1. Define Your Folders
# ==========================================
# Where the images are right now:
real_source = '/content/drive/MyDrive/EPICS/pneumonia_dataset/pneumonia_256x256'
fake_source = '/content/drive/MyDrive/EPICS/pneumonia_dataset/fake_pneumonia'

# The brand new Master Folder for your Detective:
master_dataset = '/content/drive/MyDrive/EPICS/lung_detector_dataset'
real_dest = os.path.join(master_dataset, 'REAL')
fake_dest = os.path.join(master_dataset, 'FAKE')

# ==========================================
# 2. Build the Folders
# ==========================================
print("🏗️ Building Master Dataset Folders...")
os.makedirs(real_dest, exist_ok=True)
os.makedirs(fake_dest, exist_ok=True)

# ==========================================
# 3. Copy the Files (Safely!)
# ==========================================
def copy_files_with_progress(source_dir, dest_dir, class_name):
    # Get all files in the source folder
    files = [f for f in os.listdir(source_dir) if f.endswith(('.jpg', '.jpeg', '.png', '.JPG', '.PNG'))]

    print(f"\n📦 Packing {len(files)} {class_name} images...")
    for file_name in tqdm(files, desc=f"Copying {class_name}"):
        source_file = os.path.join(source_dir, file_name)
        dest_file = os.path.join(dest_dir, file_name)

        # Only copy if it isn't already there (saves time if you have to restart!)
        if not os.path.exists(dest_file):
            shutil.copy(source_file, dest_file)

# Copy the Reals
copy_files_with_progress(real_source, real_dest, "REAL")

# Copy the Fakes
copy_files_with_progress(fake_source, fake_dest, "FAKE")

print(f"\n✅ Dataset Reorganization Complete!")
print(f"Your Master Training Folder is ready at: {master_dataset}")

"""Files Overlooker"""

import os
fake_dest = '/content/drive/MyDrive/EPICS/lung_detector_dataset/FAKE'
real_dest = '/content/drive/MyDrive/EPICS/lung_detector_dataset/REAL'

print("Checking the actual hard drive...")
print(f"Files in REAL folder: {len(os.listdir(real_dest))}")
print(f"Files in FAKE folder: {len(os.listdir(fake_dest))}")